# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: gjKUfA8tXSUF87p7ekS2xK4gJxMbOuFF
            client-secret: v9oK2K-WpziKirsiubs-PqRp1jP3tqpovTaXHNAWdaBaYiQQcgfk-4A642WfSAis
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-kzcvxumieqdlk3zf.us.auth0.com/