# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ofzUV2bVIQAFceROYaaSryAEHsrOyFTH
            client-secret: i16mAhqQXkiamzkr7p69rT8lTH9IWVUzPw-NbnsuedDRfzV5IWHvlAyOk-FtoajJ
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-l5lamxwwwqheefsk.us.auth0.com/